#%RAML 1.0 DataType
properties:
  firstName: 
    description: firstname
    type: string
    required: true
  lastName:
    description: lastname
    type: string
    required: true
  emailId:
    description: emailid
    type: string
    required: true
  password:
    description: password
    type: string
    required: true
  phoneNumber:
    description: phonenumber
    type: string
    required: true


 


