#%RAML 1.0 NamedExample
example:
-
  "subscriptionId": "1"
  "userId": "1"
  "source_location": "Bath"
  "destination_location": "london"
  "from_time": "10:30:00"
  "to_time": "11:00:00"
  "Advance_notify_time_min": "30:00:00"
  "updatedtimestamp": "2007-11-11 T 11:20"
  "creationtimestamp": "2007-11-09 T 11:20"
  "statustypeID": "aa"
-
  "subscriptionId": "2"
  "userId": "2"
  "source_location": "Bath"
  "destination_location": "london"
  "from_time": "10:30:00"
  "to_time": "12:00:00"
  "Advance_notify_time_min": "30:00:00"
  "updatedtimestamp": "2007-11-10 T 10:20"
  "creationtimestamp": "2007-11-09 T 11:20"
  "statustypeID": "aa"